### ISSUE TITLE
Have to add photo gallery

### ISSUE THREAD

**Issue by Safnaj** [GitHubExperts-LK/GitHubExperts-LK.github.io#10]
Have to modify the blog component as galley and need to add some past event photos.

**Comment by Shehanka** [comment]
Let's find a way to get photos from GCEs Google Photos Album

**Comment by Safnaj** [comment]
> can you assign this issue to me? I can fix this issue. @Shehanka @Safnaj

done

**Comment by avinIndrasoma** [comment]
@shanjathurshan are you currently doing this?

**Comment by avinIndrasoma** [comment]
@shanjathurshan ah cool, He shared the folder link:[Google Photos Link](https://photos.app.goo.gl/Fhrn9Gdj6zqZthhC6)
