### ISSUE TITLE
Contact is not working!

### ISSUE THREAD

**Issue by sajeetharan** [GitHubExperts-LK/GitHubExperts-LK.github.io#28]
When i try to contact using the contact option, it does not seem to be working!

![image](https://user-images.githubusercontent.com/4833351/99877818-d93d8880-2c26-11eb-8549-72d0b223389e.png)

**Comment by Safnaj** [comment]
<img width="275" alt="Screenshot 2020-11-21 at 8 05 39 PM" src="https://user-images.githubusercontent.com/37530024/99879772-f0837280-2c34-11eb-98ee-3ed425b2c20e.png">

It's working. Should reset the form and show a toastr alert after the mail being sent.

**Comment by Shehanka** [comment]
> <img alt="Screenshot 2020-11-21 at 8 05 39 PM" width="275" src="https://user-images.githubusercontent.com/37530024/99879772-f0837280-2c34-11eb-98ee-3ed425b2c20e.png">
> 
> It's working. Should reset the form and show a toastr alert after the mail being sent.

Aww, Can I mention her?
