### ISSUE TITLE
In the Features section "MEET OUR TEAM" paragraph 5 GitHub campus experts text should be changed to 7 GitHub campus experts

### ISSUE THREAD

**Issue by Dilshan97** [GitHubExperts-LK/GitHubExperts-LK.github.io#33]
![image](https://user-images.githubusercontent.com/27553144/99896328-98408500-2cb5-11eb-8b5d-2da6bf2b7d59.png)

**Comment by Shehanka** [comment]
@Dilshan97 Thanks for reporting issue to us
