### ISSUE TITLE
Team Members Photos Should Display in one Row

### ISSUE THREAD

**Issue by Safnaj** [GitHubExperts-LK/GitHubExperts-LK.github.io#4]
There is a huge gap after my profile.. If anyone can make it in a single row. It would look fine

**Comment by Dilshan97** [comment]
Yeah, i can do it

**Comment by Dilshan97** [comment]
I fix this issue. But some time it contain some issues. Check it

**Comment by Safnaj** [comment]
@Dilshan97 I have added custom padding for team members name field. Now it fine..!
