### ISSUE TITLE
spellings mistake

### ISSUE THREAD

**Issue by Dilshan97** [GitHubExperts-LK/GitHubExperts-LK.github.io#42]
![image](https://user-images.githubusercontent.com/27553144/101235813-b4024d00-36f1-11eb-9f8b-11cfb8e58a62.png)

**Comment by Safnaj** [comment]
@Dilshan97 I am looking into this..
BTW we are working on our SLIIT FOSS Website too. Planning to give a prize for the Top Contributor
give a try.. https://github.com/sliit-foss/sliitfoss
