### ISSUE TITLE
Add J'Pura Foss Logo under collaborators

### ISSUE THREAD

**Issue by Safnaj** [GitHubExperts-LK/GitHubExperts-LK.github.io#70]
- [ ] Need to fix - There is a delay in SOCS logo loading time.
- [ ] Add j'pura foss community logo

**Comment by avinIndrasoma** [comment]
@Safnaj I can handle this!

**Comment by Safnaj** [comment]
@avinIndrasoma any updates ?

**Comment by avinIndrasoma** [comment]
Oh Sorry, I forgot this. Will do @Safnaj can you link an image of their logo here?

**Comment by Safnaj** [comment]
> Oh Sorry, I forgot this. Will do @Safnaj can you link their logo here?

get it [here](https://drive.google.com/drive/folders/1qOz_Gh5wwNBJ9l9WNW-aTvVR39w6JLU7)
