### ISSUE TITLE
Add Gallery Navlink to the Navbar

### ISSUE THREAD

**Issue by Safnaj** [GitHubExperts-LK/GitHubExperts-LK.github.io#71]
Add Navlink Gallary after Team and make sure its navigate to the correct section.

**Comment by JiaHua-Zou** [comment]
can you assign this to me?

**Comment by Shehanka** [comment]
> can you assign this to me?

Assigned

**Comment by JiaHua-Zou** [comment]
I have created a [PR](https://github.com/GitHubExperts-LK/GitHubExperts-LK.github.io/pull/72). Let me know if there's any adjustments to the PR.
