### ISSUE TITLE
Add Amanda's Profile

### ISSUE THREAD

**Issue by Safnaj** [GitHubExperts-LK/GitHubExperts-LK.github.io#75]
Add Amanda's Data to the below location :
https://github.com/GitHubExperts-LK/GitHubExperts-LK.github.io/blob/development/src/assets/data/experts.json

**Comment by Dilshan97** [comment]
@Safnaj check #85

**Comment by Safnaj** [comment]
> @Safnaj check #85

Merged, Thanks !!
