### ISSUE TITLE
Remove old build files 

### ISSUE THREAD

**Issue by Shehanka** [GitHubExperts-LK/GitHubExperts-LK.github.io#9]

**Comment by Safnaj** [comment]
@Shehanka Cleaned, Built and Deployed..! 
Isuru's Profile Height is difference from others profile. Fix it and push it again..

**Comment by Safnaj** [comment]
Have u changed anything in Workflows or JS Files ??
URL Redirects to https://githubexperts-lk.github.io/**github-community-sl/** it should be redirect to **https://githubexperts-lk.github.io/** only
